name: top_weather
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  equatable: ^2.0.5
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  http: ^1.2.2
  hydrated_bloc: ^9.1.5
  intl: ^0.19.0
  location: ^7.0.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/weather/icon/dark/
    - assets/weather/icon/light/
    - assets/weather/background/day/
    - assets/weather/background/night/

flutter_assets:
  assets_path:
    - assets/weather/background
    - assets/weather/icon
  output_path: lib/constants/
  filename: assets.dart
  field_prefix: null
