// enum
enum ForecastIcon {
  blizzard,
  blowingSnow,
  clearNight,
  clearDay,
  cloudy,
  cloudyWithRain,
  cloudyWithSnow,
  cloudyWithSunny,
  drizzle,
  flurries,
  hazeFogDustSmoke,
  heavyRain,
  heavySnow,
  icy,
  isolatedScatteredThunderstormsDay,
  isolatedScatteredThunderstormsNight,
  isolatedThunderstorms,
  mixedRainSnow,
  mixedRainSleetHail,
  mostlyClearDay,
  mostlyClearNight,
  mostlyCloudyDay,
  mostlyCloudyNight,
  notAvailable,
  partlyCloudyDay,
  partlyCloudyNight,
  scatteredShowersDay,
  scatteredShowersNight,
  scatteredSnowShowersDay,
  scatteredSnowShowersNight,
  showersRain,
  showersSnow,
  sleetHail,
  strongThunderstorms,
  sunnyAndCloudy,
  sunnyWithRainDarkSky,
  sunnyWithSnow,
  tornado,
  tropicalStormHurricane,
  veryCold,
  veryHot,
  windyBreezy;

  String toMap() => name;
  static ForecastIcon fromMap(String name) => values.byName(name);
}
